version: '3.9'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - .postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  node:
    image: drink/drunk-on-dles-bot
